[package]
name = "markov_str"
version = "0.1.0"
authors = ["brogolem35"]
edition = "2021"
description = "Markov Chain implementation optimized for text generation."
license = "MIT"
repository = "https://github.com/Brogolem35/markov_str"
keywords = ["markov", "markov-chain", "text-generation"]
categories = ["text-processing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.14.5"
lasso = {version = "0.7.2", features = ["ahasher", "inline-more"]}
rand = "0.8.5"
regex = "1.10.6"

# [target.'cfg(not(target_env = "msvc"))'.dependencies]
# tikv-jemallocator = "0.6"

[package.metadata.clippy]
# This sets all pedantic lints to be treated as errors
deny = ["clippy::pedantic"]
